version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: djahit-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: djahit
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: djahitontop
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    networks:
      - djahit-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d djahit"]
      interval: 10s
      timeout: 5s
      retries: 5

  api:
    build: .
    container_name: djahit-api
    restart: unless-stopped
    env_file: .env
    ports:
      - "5551:5551"
    networks:
      - djahit-network
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./logs:/app/logs
    security_opt:
      - no-new-privileges:true
  yolo-api:
    build:
      context: ./yolo-api
    container_name: yolo-api
    restart: unless-stopped
    ports:
      - "8009:8000"
    networks:
      - djahit-network
    volumes:
      - ./models/best.pt:/app/runs/detect/train_pretty_save5/weights/best.pt
    environment:
      - PYTHONUNBUFFERED=1
      - YOLO_CONFIG_DIR=/app/config
    command: uvicorn main:app --host 0.0.0.0 --port 8000


  nginx:
    image: nginx:alpine
    container_name: djahit-nginx
    restart: unless-stopped
    ports:
      - "8880:8880"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - nginx_logs:/var/log/nginx  
      - ./public:/etc/nginx/html
    depends_on:
      - api
      - yolo-api
    networks:
      - djahit-network

volumes:
  postgres_data:
    driver: local
  nginx_logs: 
    driver: local

networks:
  djahit-network:
    driver: bridge
